-- =====================================================
-- C.O.G.N.I.T. Images Seed Data
-- Contains full GitHub raw URLs for all survey images
-- =====================================================

INSERT INTO images (image_id, image_url, difficulty_score, object_count, width, height) VALUES
('survey/attention-circle.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/attention-circle.svg', 5.0, 1, 800, 600),
('survey/attention-ocean.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/attention-ocean.svg', 5.0, 1, 800, 600),
('survey/attention-red.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/attention-red.svg', 5.0, 1, 800, 600),
('survey/aurora-lake.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/aurora-lake.svg', 5.0, 1, 800, 600),
('survey/bunny-garden.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/bunny-garden.svg', 5.0, 1, 800, 600),
('survey/cat-play.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cat-play.svg', 5.0, 1, 800, 600),
('survey/coral-reef.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/coral-reef.svg', 5.0, 1, 800, 600),
('survey/cute-alpaca.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-alpaca.svg', 5.0, 1, 800, 600),
('survey/cute-bear.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-bear.svg', 5.0, 1, 800, 600),
('survey/cute-bunny.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-bunny.svg', 5.0, 1, 800, 600),
('survey/cute-calf.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-calf.svg', 5.0, 1, 800, 600),
('survey/cute-chick.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-chick.svg', 5.0, 1, 800, 600),
('survey/cute-deer.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-deer.svg', 5.0, 1, 800, 600),
('survey/cute-dolphin.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-dolphin.svg', 5.0, 1, 800, 600),
('survey/cute-duck.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-duck.svg', 5.0, 1, 800, 600),
('survey/cute-elephant.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-elephant.svg', 5.0, 1, 800, 600),
('survey/cute-fox.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-fox.svg', 5.0, 1, 800, 600),
('survey/cute-frog.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-frog.svg', 5.0, 1, 800, 600),
('survey/cute-giraffe.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-giraffe.svg', 5.0, 1, 800, 600),
('survey/cute-hedgehog.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-hedgehog.svg', 5.0, 1, 800, 600),
('survey/cute-kitten.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-kitten.svg', 5.0, 1, 800, 600),
('survey/cute-koala.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-koala.svg', 5.0, 1, 800, 600),
('survey/cute-lamb.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-lamb.svg', 5.0, 1, 800, 600),
('survey/cute-lion.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-lion.svg', 5.0, 1, 800, 600),
('survey/cute-otter.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-otter.svg', 5.0, 1, 800, 600),
('survey/cute-owl.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-owl.svg', 5.0, 1, 800, 600),
('survey/cute-panda.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-panda.svg', 5.0, 1, 800, 600),
('survey/cute-penguin.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-penguin.svg', 5.0, 1, 800, 600),
('survey/cute-piglet.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-piglet.svg', 5.0, 1, 800, 600),
('survey/cute-puppy.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-puppy.svg', 5.0, 1, 800, 600),
('survey/cute-raccoon.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-raccoon.svg', 5.0, 1, 800, 600),
('survey/cute-seal.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-seal.svg', 5.0, 1, 800, 600),
('survey/cute-sloth.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-sloth.svg', 5.0, 1, 800, 600),
('survey/cute-squirrel.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-squirrel.svg', 5.0, 1, 800, 600),
('survey/cute-tiger.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-tiger.svg', 5.0, 1, 800, 600),
('survey/cute-turtle.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-turtle.svg', 5.0, 1, 800, 600),
('survey/cute-unicorn.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/cute-unicorn.svg', 5.0, 1, 800, 600),
('survey/desert-dunes.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/desert-dunes.svg', 5.0, 1, 800, 600),
('survey/dog-sunny.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/dog-sunny.svg', 5.0, 1, 800, 600),
('survey/forest-stream.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/forest-stream.svg', 5.0, 1, 800, 600),
('survey/fox-cloud.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/fox-cloud.svg', 5.0, 1, 800, 600),
('survey/glacier-bay.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/glacier-bay.svg', 5.0, 1, 800, 600),
('survey/golden-temple.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/golden-temple.svg', 5.0, 1, 800, 600),
('survey/hamster-wheel.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/hamster-wheel.svg', 5.0, 1, 800, 600),
('survey/harbor-dawn.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/harbor-dawn.svg', 5.0, 1, 800, 600),
('survey/kitten-yarn.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/kitten-yarn.svg', 5.0, 1, 800, 600),
('survey/lavender-fields.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/lavender-fields.svg', 5.0, 1, 800, 600),
('survey/midnight-city.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/midnight-city.svg', 5.0, 1, 800, 600),
('survey/misty-valley.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/misty-valley.svg', 5.0, 1, 800, 600),
('survey/moonlit-meadow.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/moonlit-meadow.svg', 5.0, 1, 800, 600),
('survey/northern-peaks.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/northern-peaks.svg', 5.0, 1, 800, 600),
('survey/orchid-garden.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/orchid-garden.svg', 5.0, 1, 800, 600),
('survey/puppy-ball.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/puppy-ball.svg', 5.0, 1, 800, 600),
('survey/rainbow-cliff.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/rainbow-cliff.svg', 5.0, 1, 800, 600),
('survey/redwood-trail.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/redwood-trail.svg', 5.0, 1, 800, 600),
('survey/river-canyon.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/river-canyon.svg', 5.0, 1, 800, 600),
('survey/rolling-hills.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/rolling-hills.svg', 5.0, 1, 800, 600),
('survey/rose-castle.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/rose-castle.svg', 5.0, 1, 800, 600),
('survey/saffron-market.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/saffron-market.svg', 5.0, 1, 800, 600),
('survey/sample-normal.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/sample-normal.svg', 5.0, 1, 800, 600),
('survey/sapphire-falls.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/sapphire-falls.svg', 5.0, 1, 800, 600),
('survey/savanna-sunset.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/savanna-sunset.svg', 5.0, 1, 800, 600),
('survey/sea-arch.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/sea-arch.svg', 5.0, 1, 800, 600),
('survey/serene-pond.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/serene-pond.svg', 5.0, 1, 800, 600),
('survey/silk-road.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/silk-road.svg', 5.0, 1, 800, 600),
('survey/silver-bridge.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/silver-bridge.svg', 5.0, 1, 800, 600),
('survey/starry-dunes.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/starry-dunes.svg', 5.0, 1, 800, 600),
('survey/sunlit-bay.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/sunlit-bay.svg', 5.0, 1, 800, 600),
('survey/tropical-lagoon.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/tropical-lagoon.svg', 5.0, 1, 800, 600),
('survey/violet-harbor.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/violet-harbor.svg', 5.0, 1, 800, 600),
('survey/whispering-glade.svg', 'https://raw.githubusercontent.com/GauravKaloliya/DL_PROJECT/main/backend/images/survey/whispering-glade.svg', 5.0, 1, 800, 600)
ON CONFLICT (image_id) DO UPDATE SET
    image_url = EXCLUDED.image_url,
    difficulty_score = EXCLUDED.difficulty_score,
    object_count = EXCLUDED.object_count,
    width = EXCLUDED.width,
    height = EXCLUDED.height;
